name: build_docker

on:
  push
    #branches: [main]
    #tags:
    #  - '*.*.*'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout commit"
        uses: actions/checkout@v2
      
      - name: "Compile Latex documents"
        run: |
          
          ls
          pwd
          ./scripts/compile.sh
          ls
