name: release

on: release

jobs:
  release:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: "Pull Latex toolchain docker"
        run: docker pull blang/latex:ubuntu
      
      - name: "Compile Latex documents"
        run: ./scripts/compile.sh

      - name: "Upload to release"
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/wouter_dankers_cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}